version: "3.9"

services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: wildlife_user
      POSTGRES_PASSWORD: wildlife_pass
      POSTGRES_DB: wildlife_db
    ports:
      - "5433:5432"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    depends_on:
      - postgres
      - mongo
    environment:
      DATABASE_URL: postgresql+psycopg2://wildlife_user:wildlife_pass@postgres:5432/wildlife_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/app/ml_models:/app/app/ml_models

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"